### ISSUE TITLE
Fonctionnalité de l'application

### ISSUE THREAD

**Issue by Abdou00** [PolesProd/AppEV#1]
J'ai crée une base pour l'app espace vert, pour l'instant on peut via le formulaire ajouté une personne ou en trouver une. Bien que cela n'est rien à voir avec les données que l'on souhaite intégrer dans notre app, c'est le fonctionnement globale qui est ici intéressant. J'aimerais savoir qu'est ce qu'on est censé faire avec l'app:
- Répertorier les parcelles(Toute ou seulement les notres)
- Localiser les parcelles sur la carte
C'est tous ce que je vois, serait-il possible d'avoir un recueil des besoins ou la liste des fonctionnalités de l'app.
Merci

**Comment by adricen** [comment]
Super, 

Bon la carte commence a dater mais je vais mettre le nez dedans. Vus que l'inoguration est passé maintenant.

A toot
